//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentations
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBadge
    {
        public long Id { get; set; }
        public long GroupMembershipId { get; set; }
        public long BadgeId { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Badge Badge { get; set; }
        public virtual GroupMembership GroupMembership { get; set; }
    }
}
